Added ToS Page
codeclubs-dot-org/codeclubs.org pull request #14
Opened 2021-04-08 01:15 UTC by saminacodes

Changed formatting of ToS page from standard HTML/CSS to Material UI Syntax.

2021-04-08 01:58 UTC, Sixstring982 approved these changes

2021-04-08 01:58 UTC, Sixstring982 commented on src/components/TeamMemberCard.js
> +// import GetAppIcon from '@material-ui/icons/GetApp'
Let's remove this comment

2021-04-08 01:58 UTC, Sixstring982 commented on src/components/TeamMemberCard.js
> +const useStyles = makeStyles((theme) => ({
Is it possible to add screenshots of this to the PR description?

It's hard to review CSS changes without some screenshots.

2021-04-08 01:58 UTC, Sixstring982 commented on src/components/TeamMemberCard.js
> +          align="center"
Can these styles be put in the `useStyles` block above?

2021-04-08 01:58 UTC, Sixstring982 commented on src/components/teamCard.js
> +    maxWidth: 360,
Is this in pixels? Generally things will scale better if we use `rem`s.

2021-04-08 01:58 UTC, Sixstring982 commented on src/components/teamCard.js
> +    backgroundColor: "#aeda4e",
We should use constants for this kind of thing to keep colors consistent across the app.

2021-04-08 01:58 UTC, Sixstring982 commented on src/components/teamCard.js
> +    marginTop: "3em",
Nit: Generally `rem` is better than `em` here too, if this component is rendered somewhere with larger font in the parent it'll look different.

2021-04-08 01:58 UTC, Sixstring982 commented on src/components/teamCard.js
> +  let cardColor;
Nit: Write a function for this instead to avoid mutable state:

const cardClass = computeCardClass(color);

...

```
const computeCardColor = (color: string): string|undefined => {
  switch (color) {
    case 'blue': return classes.blue;
    case 'pink': return classes.pink;
    ...
  }
  return undefined;
};
```

2021-04-08 01:58 UTC, Sixstring982 commented on src/components/teamCard.js
> +  let cardColor;
Where is this used?

2021-04-08 01:58 UTC, Sixstring982 commented on src/components/teamCard.js
> +    maxWidth: 360,
Better yet, what about the `theme.spacing` functions?

2021-04-08 01:58 UTC, Sixstring982 commented on src/views/home/PrivacyView/index.js
> +          <Typography variant="p">Last updated: March 01, 2021. </Typography>
Nit: Maybe just leave the date out, not sure how accurate this needs to be from a legal standpoint.

2021-04-08 01:58 UTC, Sixstring982 commented on src/views/home/PrivacyView/index.js
> +          <Typography variant="p">
This Typography stuff is weird from first glance; why not just use a `p` tag?

2021-04-08 01:58 UTC, Sixstring982 commented on src/views/home/PrivacyView/index.js
> +            This Privacy Policy describes Our policies and procedures on the
Where is this text coming from? It'd probably be good to link to the original source somewhere, maybe in a comment?

2021-04-08 01:58 UTC, Sixstring982 commented on src/views/home/PrivacyView/index.js
> +};
We should probably get someone else to take a closer look at this privacy policy, I can only read so much legalese. :dizzy_face:

2021-04-08 01:58 UTC, Sixstring982 commented on src/views/home/PrivacyView/index.js
> +              <Typography variant="p">By phone number: 505-600-1775</Typography>
Nit: Phone number tag?

```
<a href="tel:5056001775">505-600-1775</a>
```

2021-04-08 01:58 UTC, Sixstring982 commented on src/views/home/PrivacyView/index.js
> +                By email: pperez@codeclubs.org
Nit: email tag?

```
<a href="mailto:pperez@codeclubs.org">pperez@codeclubs.org</a>

```

2021-04-08 16:29 UTC, saminacodes commented on src/components/TeamMemberCard.js
> +// import GetAppIcon from '@material-ui/icons/GetApp'
Actually I will delete this file because the updated one I had added is called teamCard.js... this one was from the template and we are not using it.

2021-04-08 17:03 UTC, saminacodes commented on src/views/home/PrivacyView/index.js
> +};
@paul-perez

2021-04-08 17:05 UTC, saminacodes commented on src/views/home/PrivacyView/index.js
> +          <Typography variant="p">
I think it's because we want to keep it consistent with the styling from our Material UI Theme. Do you think we should change it?

2021-04-24 05:23 UTC, saminacodes commented on src/components/teamCard.js
> +  let cardColor;
I will add this function later because we have not integrated typescript. We can have all the cards be a single color for now

2021-04-28 23:34 UTC, Sixstring982 requested changes

2021-04-28 23:34 UTC, Sixstring982 commented on src/views/home/InvolvedView/index.js
> +      <p>test</p>
Is there a reason this component is new? What does it do? Looks like nothing at the moment; maybe we should remove it?

2021-04-28 23:34 UTC, Sixstring982 commented on src/App.js
> +import 'react-perfect-scrollbar/dist/css/styles.css'
Can we revert this standard JS commit? Let's do that in another PR, it's hard to review this alongside your other changes.

2021-04-29 01:10 UTC, closed without merging

2021-04-29 01:11 UTC, saminacodes commented
Too many features/bugs addressed. Separate the concerns into different branches.